name: Solidity CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Use Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Install black
        run: pip install black
      - name: Install Dependencies
        run: yarn
      - name: Lint Contracts
        run: yarn run lint

  scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run CPMM V2 scripts
        run: rm -rf build/contracts build/interfaces && brownie run scripts/show_gas_usage_cpmmv2.py
      - name: Run CPMM V3 scripts
        run: rm -rf build/contracts build/interfaces && brownie run scripts/show_gas_usage_cpmmv3.py
      - name: Run CEMM scripts
        run: rm -rf build/contracts build/interfaces && brownie run scripts/show_gas_usage_cemm.py

  unit_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: brownie test -m 'not hypothesis'

  property_test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run property Tests
        run: brownie test --hypothesis-seed=42 --failfast -m hypothesis
